name: Simple Android Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
          
      - name: Install Libraries
        run: |
          haxelib install lime 8.1.2
          haxelib install openfl 9.3.3
          haxelib install flixel 5.5.0
          haxelib install flixel-addons 3.2.2
          haxelib install flixel-ui 2.5.0
          haxelib install hscript 2.5.0
          haxelib install flixel-tools 1.5.1
          haxelib install actuate 1.9.0
          haxelib install extension-androidtools
          haxelib install tjson
          haxelib install hxcpp
          
      - name: Setup Lime
        run: |
          haxelib run lime setup
          haxelib run lime setup flixel
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build APK
        run: |
          haxelib run lime build android -final
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PsychEngine-Android
          path: |
            export/release/android/bin/*.apk
            export/release/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
